//GAME STATUS == OK ---> THE GAME RUNS NORMALLY
//GAME STATUS == CRASH ---> IT MEANS THERE HAS BEEN A CRASH BETWEEN SHARK AND PLAYER
//GAME STATUS == GAMEOVER --->YOU LOST ALL THE LIVES
//GAME STATUS == START ---> JUST STARTING THE GAME

enum Status {OK, CRASH, GAMEOVER, START}
